[package]
name = "presburger"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = {version = "0.19.0", features = ["lexer"]}

[dependencies]
lalrpop-util = "0.19.0"
proptest = "0.10.0"
rand = "0.7"
regex = "1.3.9"
