[package]
name = "presburger"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2021"

[dependencies]
lalrpop = "^0.20"
lalrpop-util = "^0.20"
proptest = "^1.1"
# TODO: eventually depend on rug for integers
# rug = "1.21.0"

[build-dependencies]
lalrpop = "^0.20"
