[package]
name = "presburger"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2021"

[dependencies]
lalrpop = "^0.20"
lalrpop-util = "^0.20"
proptest = "^1.1"
rand = "^0.8"
regex = "^1.7"

[build-dependencies]
lalrpop = "^0.20"
