[package]
name = "presburger"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2024"

[dependencies]
lalrpop = "^0.22"
lalrpop-util = "^0.22"
proptest = "^1.6"
num-rational = "^0.4"

[build-dependencies]
lalrpop = "^0.22"
