[package]
name = "presburger"
version = "0.1.0"
authors = ["Benjamin Jones <benjaminfjones@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = {version = "0.19.7", features = ["lexer"]}

[dependencies]
lalrpop-util = "0.19.7"
proptest = "1.0.0"
rand = "0.8"
regex = "1.5.5"
